name: Deploy example website

on:
  push:
    branches:
      - main

jobs:
  github-deploy:
    if: github.repository == 'vue3-plugins/vue3-plugins.github.io'
    name: Deploying website
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    steps:
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - name: Checkout website code
        uses: actions/checkout@v4

      - name: Install packages
        shell: bash
        run: |
          yarn install

      - name: Build website
        shell: bash
        run: |
          yarn build
  
      - name: Deploy
        shell: bash
        run: |
          git config user.name "GitHub Action" && git config user.email "github-action@users.noreply.github.com"
          git checkout --orphan dist
          touch dist/.nojekyll
          git --work-tree dist add --all
          git --work-tree dist commit -m "Commit new changes to website."
          git push origin HEAD:website --force
